[package]
version = "0.1.3"
name = "intelli"
edition = "2021"
readme = "README.md"
rust-version = "1.72.0"
description = "F123 Championship Tool"
authors = ["Gpeaky <gerardjoven2020@hotmail.com>"]
license = "MIT"
repository = "https://github.com/GPeaky/intelli-api"

[dependencies]
rand = "0.8.5"
ahash = "0.8.3"
garde = "0.15.0"
bcrypt = "0.15.0"
dotenvy = "0.15.7"
tracing = "0.1.37"
rmp-serde = "1.1.2"
thiserror = "1.0.48"
serde_trim = "1.0.0"
jsonwebtoken = "8.3.0"
serde-big-array = "0.5.1"
tracing-subscriber = "0.3.17"
tokio = { version = "1.32.0", features = ["full"] }
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive"] }
redis = { version = "0.23.3", features = ["tokio-comp"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio", "mysql", "chrono"] }
hyper = { version = "0.14.27", features = ["http2", "full"] }
lettre = { version = "0.10.4", default-features = false, features = [
    "tokio1-rustls-tls",
    "smtp-transport",
    "builder",
] }
axum = { version = "0.6.20", features = [
    "form",
    "macros",
    "multipart",
    "headers",
    "http2",
    "ws",
] }
tower = { version = "0.4.13", features = [
    "limit",
    "buffer",
    "tokio",
    "timeout",
    "load-shed",
] }
tower-http = { version = "0.4.4", features = [
    "cors",
    "fs",
    "tokio",
] }

[profile.release]
debug = 0
lto = "fat"
opt-level = 3
codegen-units = 1
split-debuginfo = "off"
panic = "abort"
