[package]
name = "intelli"
edition = "2021"
version = "0.3.0"
readme = "README.md"
description = "F123 Championship Tool"
authors = ["Gpeaky <gerardjoven2020@hotmail.com>"]
repository = "https://github.com/GPeaky/intelli-api"
license = "MIT"

[build-dependencies]
prost-build = "0.12.2"

[dependencies]
rand = "0.8.5"
prost = "0.12.2"
garde = "0.16.2"
askama = "0.12.1"
bcrypt = "0.15.0"
tracing = "0.1.40"
dotenvy = "0.15.7"
mimalloc = "0.1.39"
rustc-hash = "1.1.0"
once_cell = "1.18.0"
thiserror = "1.0.50"
serde_trim = "1.0.0"
bb8-redis = "0.13.1"
jsonwebtoken = "9.1.0"
tokio = { version = "1.34.0", features = ["full"] }
hyper = { version = "0.14.27", features = [
    "full",
] } # Waiting Axum & Reqwest updates to update to 1.0.1
serde = { version = "1.0.192", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["json"] }
zerocopy = { version = "0.7.26", features = ["derive"] }
chrono = { version = "0.4.31", features = ["serde", "rkyv"] }
tower-http = { version = "0.4.4", features = ["cors", "tokio"] }
rkyv = { version = "0.7.42", features = ["bytecheck", "validation"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tower = { version = "0.4.13", features = ["tokio", "timeout", "load-shed"] }
axum = { version = "0.6.20", features = ["form", "macros", "headers", "ws"] }
lettre = { version = "0.11.1", default-features = false, features = [
    "tokio1-rustls-tls",
    "smtp-transport",
    "builder",
] }
bb8-postgres = { version = "0.8.1", features = ["with-chrono-0_4"] }
postgres-types = { version = "0.2.6", features = ["derive", "with-chrono-0_4"] }


[profile.release]
debug = 0
lto = "fat"
opt-level = 3
codegen-units = 1
split-debuginfo = "off"
# panic = "abort"
