[package]
version = "0.1.5"
name = "intelli"
edition = "2021"
readme = "README.md"
rust-version = "1.72.0"
description = "F123 Championship Tool"
authors = ["Gpeaky <gerardjoven2020@hotmail.com>"]
repository = "https://github.com/GPeaky/intelli-api"
license = "MIT"

[build-dependencies]
prost-build = "0.12.1"

[dependencies]
prost = "0.12.1"
garde = "0.15.0"
bcrypt = "0.15.0"
rustls = "0.21.7"
tracing = "0.1.37"
dotenvy = "0.15.7"
mimalloc = "0.1.39"
rustc-hash = "1.1.0"
once_cell = "1.18.0"
thiserror = "1.0.48"
serde_trim = "1.0.0"
jsonwebtoken = "8.3.0"
rustls-pemfile = "1.0.3"
serde-big-array = "0.5.1"
tokio = { version = "1.33.0", features = ["full"] }
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["json"] }
redis = { version = "0.23.3", features = ["tokio-comp"] }
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
hyper-rustls = { version = "0.24.1", features = ["http2"] }
hyper = { version = "0.14.27", features = ["http2", "full"] }
tower-http = { version = "0.4.4", features = ["cors", "fs", "tokio"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
sqlx = { version = "0.7.2", features = ["runtime-tokio", "mysql", "chrono"] }
lettre = { version = "0.10.4", default-features = false, features = [
    "tokio1-rustls-tls",
    "smtp-transport",
    "builder",
] }
axum = { version = "0.6.20", features = [
    "form",
    "macros",
    "multipart",
    "headers",
    "http2",
    "ws",
] }
tower = { version = "0.4.13", features = [
    "limit",
    "buffer",
    "tokio",
    "timeout",
    "load-shed",
] }
rand = "0.8.5"

[profile.release]
debug = 0
lto = "fat"
opt-level = 3
codegen-units = 1
split-debuginfo = "off"
#panic = "abort"
