[package]
name = "intelli"
edition = "2021"
version = "0.2.1"
readme = "README.md"
description = "F123 Championship Tool"
authors = ["Gpeaky <gerardjoven2020@hotmail.com>"]
repository = "https://github.com/GPeaky/intelli-api"
license = "MIT"

[build-dependencies]
prost-build = "0.12.1"

[dependencies]
garde = "0.16.2"
bcrypt = "0.15.0"
tracing = "0.1.40"
dotenvy = "0.15.7"
mimalloc = "0.1.39"
rustc-hash = "1.1.0"
once_cell = "1.18.0"
thiserror = "1.0.50"
serde_trim = "1.0.0"
jsonwebtoken = "9.1.0"
tokio = { version = "1.33.0", features = ["full"] }
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.192", features = ["derive"] }
reqwest = { version = "0.11.22", features = ["json"] }
redis = { version = "0.23.3", features = ["tokio-comp"] }
hyper = { version = "0.14.27", features = ["full"] }
tower-http = { version = "0.4.4", features = ["cors", "fs", "tokio"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
sqlx = { version = "0.7.2", features = ["runtime-tokio", "mysql", "chrono"] }
lettre = { version = "0.11.1", default-features = false, features = [
    "tokio1-rustls-tls",
    "smtp-transport",
    "builder",
] }
axum = { version = "0.6.20", features = [
    "form",
    "macros",
    "multipart",
    "headers",
    "http2",
    "ws",
] }
tower = { version = "0.4.13", features = [
    "limit",
    "buffer",
    "tokio",
    "timeout",
    "load-shed",
] }
rand = "0.8.5"
prost = "0.12.1"
askama = "0.12.1"
zerocopy = { version = "0.7.25", features = ["derive"] }

[profile.release]
debug = 0
lto = "fat"
opt-level = 3
codegen-units = 1
split-debuginfo = "off"
#panic = "abort"
