version: "3.8"

volumes:
  keydb-data: {}

services:
  api:
    build: .
    network_mode: host
    restart: unless-stopped
    container_name: intelli-api
    depends_on:
      - keydb

    environment:
      - HOST
      - REDIS_URL
      - DATABASE_URL
      - EMAIL_HOST
      - EMAIL_FROM
      - EMAIL_NAME
      - EMAIL_PASS
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_REDIRECT_URI
      - GOOGLE_GRANT_TYPE

  keydb:
    container_name: keydb
    image: eqalpha/keydb
    restart: unless-stopped

    ports:
      - 127.0.0.1:6379:6379

    volumes:
      - keydb-data:/data