version: "3.8"

services:
  api:
    container_name: intelli-api
    build: .
    ports:
      - "443:443"
      - "20777-20899:20777-20899/udp"

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

    env_file:
      - .env
