name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted
    environment: intelli

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build with Docker Compose
        run: docker-compose build

      - name: Run with Docker Compose
        run: docker-compose up -d
