name: Rust CI

on:
  - push
  - pull_request

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Cap'n Proto
            run: |
              sudo apt-get update
              sudo apt-get install -y capnproto

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  lints:
    name: Lints
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Cap'n Proto
            run: |
              sudo apt-get update
              sudo apt-get install -y capnproto

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
