name: Rust CI

on:
  - push
  - pull_request

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install FlatBuffers
        run: |
          wget https://github.com/google/flatbuffers/releases/download/v2.0.0/flatc_linux_x86_64
          chmod +x flatc_linux_x86_64
          sudo mv flatc_linux_x86_64 /usr/local/bin/flatc

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  lints:
    name: Lints
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install FlatBuffers
        run: |
          wget https://github.com/google/flatbuffers/releases/download/v2.0.0/flatc_linux_x86_64
          chmod +x flatc_linux_x86_64
          sudo mv flatc_linux_x86_64 /usr/local/bin/flatc

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
